### ISSUE TITLE
console.log qui s'affiche lors de l'utilisation du widget GrilleDay

### ISSUE THREAD

**Issue by wildmatthieu** [WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style#25]
Lorsqu'on clique sur les lignes dans le widget GrilleDay, des console.log s'affichent

![image](https://github.com/WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style/assets/144900231/1e76e503-6d56-4d6c-a922-a72311ff2044)

**Comment by messaoudisony** [comment]
Merci le retour.
