### ISSUE TITLE
doc import

### ISSUE THREAD

**Issue by HazeFury** [WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style#29]
dans les exemples de code de la doc, il faut importer le useState from "react" directement dans votre exemple pour faciliter la mise en place => il faut que quand je colle le code, cela marche directement

**Comment by Bak-Faek** [comment]
Bonjour, 
Merci pour ce retour, cela peux en effet poser problème.
Le nécessaire sera apporter à notre nouvelle version.
