### ISSUE TITLE
Faute dans le README

### ISSUE THREAD

**Issue by techmefr** [WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style#34]
Capture image au lieu de capture d'écran

**Comment by sdp971** [comment]
Pourrais-tu s'il te plait expliciter ton issue ? En quoi c'est une erreur ? Je te remercie d'avance pour ton retour

**Comment by techmefr** [comment]
juste on dit capture d'écran et pas capture image et merci pour votre inspiration avec les icônes on va reprendre votre idée :)

**Comment by sdp971** [comment]
My bad, je n'avais pas compris 🤣 ! De rien pour les icônes 😊
