### ISSUE TITLE
Utilisation > Example d'utilisation des composants > fontFamily="Roboto"

### ISSUE THREAD

**Issue by JohLav** [WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style#35]
The following code doesn't seem to take into account the `fontFamily="Roboto"` personalisation:

```js
<CalendarCases
   language="fr"
   color="red"
   fontFamily="Roboto"
   backgroundColor="white"
/>
```
<img width="367" alt="Capture d’écran 2024-04-30 à 11 18 55" src="https://github.com/WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style/assets/115481046/a9634bed-fb2a-4dfa-aeee-d1a47cb26645">

I use the Firefox Developer browser

**Comment by Bak-Faek** [comment]
Bonjour, 
Merci pour votre retour,
il faut en effet importer la police "Roboto" dans votre projet pour pouvoir l'utiliser.
Nous allons modifier notre exemple pour éviter le les futurs problèmes.
