### ISSUE TITLE
- DOC - Missing export in example

### ISSUE THREAD

**Issue by brrrrrbrrrr** [WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style#36]
The export is missing in the code provided in the example. I stupidly pasted the code into another component to test, and it didn't work because of that :D

``` js
import { CalendarCases } from "react-calendar-style";

function App() {
  return (
    <>
      <CalendarCases
        language="fr"
        color="red"
        fontFamily="Roboto"
        backgroundColor="white"
      />
    </>
  );
}
```

missing code : 
``` js 
export default App;
```

Thank you !

**Comment by Bak-Faek** [comment]
Bonjour et merci pour ce retour,
ça peut en effet porter à confusion, nous allons apporter cette modification sur notre prochaine version.
