### ISSUE TITLE
InputDate > README example width="30%" 

### ISSUE THREAD

**Issue by JohLav** [WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style#37]
The following code works fine! However, the default width should not be 30% but 100%, otherwise we cannot see the whole date in the input.

```js
import { InputDate } from "react-calendar-style";

function App() {
  const currentDate = new Date();
  const [date, setDate] = useState(currentDate);

  return (
    <div className="app">
      <InputDate
        value={date}
        setValue={setDate}
        height="40px"
        width="30%"
        background="white"
        color="green"
        fontFamily="Arial"
        border="3px solid grey"
        borderRadius="5px"
      />
    </div>
  );
}
```
<img width="118" alt="Capture d’écran 2024-04-30 à 11 25 48" src="https://github.com/WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style/assets/115481046/d901e0db-fc7c-4212-bc83-e96142235809">

**Comment by messaoudisony** [comment]
Merci pour le retours. ca sera corrigé
