### ISSUE TITLE
erreurs dans la console

### ISSUE THREAD

**Issue by techmefr** [WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style#38]
![Capture d’écran du 2024-04-30 11-20-01](https://github.com/WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style/assets/51131564/67ba496b-80c4-4bbf-a6dc-91faec8f4af1)
![Capture d’écran du 2024-04-30 11-19-30](https://github.com/WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style/assets/51131564/f6a4b46d-4d7f-4938-b5cc-f008875261ae)
![Capture d’écran du 2024-04-30 11-19-13](https://github.com/WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style/assets/51131564/5c4a2a75-77be-4fd4-9c10-8a87675b759a)

juste au lancement du composant

**Comment by hamed-cell** [comment]
j'ai le meme souci

**Comment by Bak-Faek** [comment]
Bonjour et merci pour vos retours, 
il manquait en effet des lignes dans l'exemple de code partagé.
Nous allons apporter les modification nécessaire pour notre prochaine version.
