### ISSUE TITLE
changement de taille en fonction du mois

### ISSUE THREAD

**Issue by techmefr** [WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style#39]
![Capture d’écran du 2024-04-30 11-33-32](https://github.com/WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style/assets/51131564/ab0fd494-a977-47dc-948c-0ef138eea91d)
![Capture d’écran du 2024-04-30 11-33-28](https://github.com/WildCodeSchool-CDA-LYON-02-2024/P2-react-calendar-style/assets/51131564/303643e9-5e7e-4ffa-9327-246131ce34a8)
quand je change de mois cela change la taille du composant

**Comment by Bak-Faek** [comment]
Bonjour, merci pour votre retour.
Il ne s'agit pas de la taille du composant qui change, mais des dates qui changent en fonction des jours de la semaine.
Nous allons faire des modifications pour ajouter les jours de la semaine au composant.
